version: '3.7'

services:
  postgres_db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=praktikum
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
